version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: notes_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: "mongodb://mongo:27017"
      MONGODB_NAME: "notes"
    volumes:
      - ./:/app  # Monta el directorio actual en /app para desarrollo

volumes:
  mongo_data:
